[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[functions]
  node_bundler = "esbuild" 